[package]
name = "Eos"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
tokio-serial = "5.4"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
postcard = { version = "1.0", features = ["alloc"] }
re_ui = "0.20.0"
